services:
  payments_api:
    build: .
    container_name: payments_api 
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    ports:
      - "5009:5009"
    networks:
      - labo08-network
    depends_on:
      - mysql_payments

  mysql_payments:
    image: mysql:8.4.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: labo05_payments_db
      MYSQL_USER: labo05
      MYSQL_PASSWORD: labo05
    # ports:
    #   - "3306:3306"
    networks:
      - labo08-network
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

networks:
  labo08-network:
    external: true 

volumes:
  mysql_data:
